/**
 * @file GenrePlaylistCreatorTest.java
 * @brief Classe di test per la generazione automatica di playlist per genere musicale.
 *
 * @details Verifica il corretto comportamento di GenrePlaylistCreator:
 *          - filtraggio case-insensitive per genere,
 *          - restituzione di null in assenza di tracce corrispondenti,
 *          - attributo isAutoGenerated = true,
 *          - nome della playlist uguale al genere,
 *          - costruttore con input non validi.
 *
 * @pattern Factory Method — ConcreteCreator: GenrePlaylistCreator
 * @see GenrePlaylistCreator
 * @see PlaylistCreator
 * @see Playlist
 * @see Track
 *
 * @author Emanuela Graziuso
 */
package it.unisa.diem.sad_gruppo6.controllers;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.factory.GenrePlaylistCreator;

public class GenrePlaylistCreatorTest {

    private List<Track> tracks;

    /**
     * Metodo di setup eseguito prima di ogni singolo test (@BeforeEach).
     * Crea una lista pulita di tracce con generi diversi da utilizzare come input del factory.
     * I file mp3 vengono creati come file temporanei reali per soddisfare il vincolo
     * di esistenza del path imposto dal costruttore di Track.
     */
    @BeforeEach
    public void setUp() throws Exception {
        // Creazione di file temporanei .mp3 reali (richiesto da Track.setPath)
        File f1 = File.createTempFile("track1_", ".mp3"); f1.deleteOnExit();
        File f2 = File.createTempFile("track2_", ".mp3"); f2.deleteOnExit();
        File f3 = File.createTempFile("track3_", ".mp3"); f3.deleteOnExit();
        File f4 = File.createTempFile("track4_", ".mp3"); f4.deleteOnExit();
        File f5 = File.createTempFile("track5_", ".mp3"); f5.deleteOnExit();

        tracks = new ArrayList<>();

        // Traccia 1 — genere: Rock
        tracks.add(new Track("Traccia A", "Autore A", 354, "Rock",  1975, f1.getAbsolutePath()));
        // Traccia 2 — genere: Rock (diverso artista)
        tracks.add(new Track("Traccia B", "Autore B", 255, "Rock",  1980, f2.getAbsolutePath()));
        // Traccia 3 — genere: Pop
        tracks.add(new Track("Traccia C", "Autore C", 233, "Pop",   2017, f3.getAbsolutePath()));
        // Traccia 4 — genere: Jazz
        tracks.add(new Track("Traccia D", "Autore D", 562, "Jazz",  1959, f4.getAbsolutePath()));
        // Traccia 5 — genere: rock (minuscolo, per test case-insensitive)
        tracks.add(new Track("Traccia E", "Autore E", 301, "rock",  1991, f5.getAbsolutePath()));
    }

    /**
     * Verifica che il creator produca una playlist con tutte e sole le tracce
     * il cui genere coincide (case-insensitive) con quello specificato.
     * Ci si aspettano 3 tracce Rock (track1, track2, track5 con "rock").
     */
    @Test
    public void testCreatePlaylistConGenereEsistente() {
        GenrePlaylistCreator creator = new GenrePlaylistCreator("Rock");
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist, "La playlist non dovrebbe essere null se esistono tracce del genere");
        assertEquals(3, playlist.getTracks().size(),
                "Dovrebbero essere presenti 3 tracce Rock (confronto case-insensitive)");
    }

    /**
     * Verifica che il nome della playlist generata coincida esattamente
     * con il genere passato al costruttore.
     */
    @Test
    public void testNomePlaylistUgualeAlGenere() {
        GenrePlaylistCreator creator = new GenrePlaylistCreator("Jazz");
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist);
        assertEquals("Jazz", playlist.getName(),
                "Il nome della playlist deve essere uguale al genere specificato");
    }

    /**
     * Verifica che la playlist prodotta abbia il flag isAutoGenerated = true,
     * come richiesto dal pattern Factory Method per le playlist automatiche.
     */
    @Test
    public void testPlaylistIsAutoGenerated() {
        GenrePlaylistCreator creator = new GenrePlaylistCreator("Pop");
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist);
        assertTrue(playlist.isAutoGenerated(),
                "La playlist generata automaticamente deve avere isAutoGenerated = true");
    }

    /**
     * Verifica che il confronto del genere sia case-insensitive:
     * cercando "POP" si devono trovare le stesse tracce di "Pop" o "pop".
     */
    @Test
    public void testFiltraggioGenereECaseInsensitive() {
        GenrePlaylistCreator creatorUpper = new GenrePlaylistCreator("POP");
        GenrePlaylistCreator creatorLower = new GenrePlaylistCreator("pop");

        Playlist playlistUpper = creatorUpper.createPlaylist(tracks);
        Playlist playlistLower = creatorLower.createPlaylist(tracks);

        assertNotNull(playlistUpper);
        assertNotNull(playlistLower);
        assertEquals(playlistUpper.getTracks().size(), playlistLower.getTracks().size(),
                "Il filtro per genere deve essere case-insensitive");
    }

    /**
     * Verifica che la playlist contenga soltanto le tracce del genere specificato
     * e che le tracce di altri generi siano escluse.
     */
    @Test
    public void testPlaylistContieneEsclusivamenteTracceDelGenere() {
        GenrePlaylistCreator creator = new GenrePlaylistCreator("Jazz");
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist);
        for (Track t : playlist.getTracks()) {
            assertTrue(t.getGenre().equalsIgnoreCase("Jazz"),
                    "Tutte le tracce della playlist devono appartenere al genere Jazz, trovato: "
                    + t.getGenre());
        }
    }

    /**
     * Verifica che il metodo getGenre() restituisca il genere
     * passato al costruttore.
     */
    @Test
    public void testGetGenereRestituisceValoreCorretto() {
        GenrePlaylistCreator creator = new GenrePlaylistCreator("Blues");
        assertEquals("Blues", creator.getGenre(),
                "getGenre() deve restituire il genere specificato nel costruttore");
    }

    /**
     * Verifica che createPlaylist() funzioni correttamente su una lista vuota,
     * restituendo null senza sollevare eccezioni.
     */
    @Test
    public void testCreatePlaylistConListaVuotaRestituisceNull() {
        GenrePlaylistCreator creator = new GenrePlaylistCreator("Rock");
        Playlist playlist = creator.createPlaylist(new ArrayList<>());

        assertNull(playlist,
                "Con una lista di tracce vuota il creator deve restituire null");
    }

    /**
     * Verifica che il creator restituisca null quando nessuna traccia
     * della libreria appartiene al genere specificato.
     */
    @Test
    public void testCreatePlaylistRestituisceNullSeNessunaTrAcciaDelGenere() {
        GenrePlaylistCreator creator = new GenrePlaylistCreator("Classical");
        Playlist playlist = creator.createPlaylist(tracks);

        assertNull(playlist,
                "Se nessuna traccia appartiene al genere, il creator deve restituire null");
    }

    /**
     * Verifica che il costruttore lanci IllegalArgumentException
     * quando viene passato un genere null.
     */
    @Test
    public void testCostruttoreConGenereNullLanciaEccezione() {
        assertThrows(IllegalArgumentException.class,
                () -> new GenrePlaylistCreator(null),
                "Il costruttore deve lanciare IllegalArgumentException per genere null");
    }

    /**
     * Verifica che il costruttore lanci IllegalArgumentException
     * quando viene passata una stringa vuota come genere.
     */
    @Test
    public void testCostruttoreConGenereVuotoLanciaEccezione() {
        assertThrows(IllegalArgumentException.class,
                () -> new GenrePlaylistCreator(""),
                "Il costruttore deve lanciare IllegalArgumentException per genere vuoto");
    }

    /**
     * Verifica che il costruttore lanci IllegalArgumentException
     * quando il genere è composto da soli spazi bianchi.
     */
    @Test
    public void testCostruttoreConGenereBlankLanciaEccezione() {
        assertThrows(IllegalArgumentException.class,
                () -> new GenrePlaylistCreator("   "),
                "Il costruttore deve lanciare IllegalArgumentException per genere blank");
    }
}