/**
 * @file HomeControllerTest.java
 * Classe di test per la validazione della logica all'interno di HomeController.
 *
 * Si concentra sulle responsabilità proprie di HomeController:
 * - Eliminazione di una playlist manuale (successo).
 * - Eliminazione con playlist autogenerata.
 * - Eliminazione con playlist null.
 * - Eliminazione di una playlist non presente in libreria.
 * - Verifica che le altre playlist rimangano intatte dopo una rimozione.
 * - Verifica che la libreria rifletta correttamente lo stato dopo le operazioni
 *
 * @author EmanuelaGraziuso
 */


package it.unisa.diem.sad_gruppo6.controllers;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import it.unisa.diem.sad_gruppo6.controller.business.playlist.PlaylistController;
import it.unisa.diem.sad_gruppo6.model.command.CommandManager;
import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.library.PlaylistLibrary;
import it.unisa.diem.sad_gruppo6.model.library.TrackLibrary;

public class HomeControllerTest {

    private PlaylistLibrary testPlaylistLibrary;
    private TrackLibrary testTrackLibrary;
    private CommandManager testCommandManager;
    private PlaylistController testPlaylistController;

    /**
     * Metodo di setup eseguito prima di ogni singolo test.
     * Riproduce la logica di HomeController#initialize():
     * recupera i singleton, li svuota per garantire isolamento, e ricrea il controller.
     */
    @BeforeEach
    public void setUp() {
        testPlaylistLibrary = PlaylistLibrary.getInstance();
        testPlaylistLibrary.clear();

        testTrackLibrary = TrackLibrary.getInstance();
        List<Track> currentTracks = new ArrayList<>(testTrackLibrary.getTracks());
        for (Track t : currentTracks) {
            testTrackLibrary.removeTrack(t);
        }

        testCommandManager = new CommandManager();
        testPlaylistController = new PlaylistController(
                testTrackLibrary, testPlaylistLibrary, testCommandManager);
    }

    /**
     * Testa la corretta eliminazione di una playlist creata manualmente.
     * Verifica che la libreria delle playlist ia vuota dopo la rimozione.
     */
    @Test
    public void testDeletePlaylist_manualPlaylist_success() {
        testPlaylistController.createPlaylist("Da eliminare");
        Playlist toDelete = testPlaylistLibrary.getPlaylists().get(0);

        testPlaylistController.deletePlaylist(toDelete);

        assertEquals(0, testPlaylistLibrary.getPlaylists().size(),
                "La libreria deve essere vuota dopo l'eliminazione");
    }

    /**
     * Verifica che, eliminando una playlist, le altre rimangano intatte
     * (la ListView deve continuare a mostrare solo quelle restanti).
     */
    @Test
    public void testDeletePlaylist_otherPlaylistsUntouched() {
        testPlaylistController.createPlaylist("Prima");
        testPlaylistController.createPlaylist("Seconda");
        Playlist first = testPlaylistLibrary.getPlaylists().get(0);

        testPlaylistController.deletePlaylist(first);

        assertEquals(1, testPlaylistLibrary.getPlaylists().size(),
                "Deve rimanere esattamente 1 playlist");
        assertEquals("Seconda", testPlaylistLibrary.getPlaylists().get(0).getName(),
                "La playlist rimasta deve essere quella non eliminata");
    }

    /**
     * Testa il tentativo di eliminare una playlist autogenerata dal sistema.
     * Verifica che venga lanciata IllegalArgumentException
     * (il controller mostra un alert "Operazione non consentita") e che
     * la libreria rimanga invariata.
     */
    @Test
    public void testDeletePlaylist_autoGeneratedThrowsException() {
        Playlist autoGenerated = new Playlist("Generata dal sistema", true);
        testPlaylistLibrary.getPlaylists().add(autoGenerated);

        assertThrows(IllegalArgumentException.class, () ->
                testPlaylistController.deletePlaylist(autoGenerated),
                "Dovrebbe lanciare un'eccezione per playlist autogenerata");

        assertTrue(testPlaylistLibrary.getPlaylists().contains(autoGenerated),
                "La playlist autogenerata non deve essere rimossa");
    }

    /**
     * Testa il tentativo di eliminare una playlist null.
     * Verifica che venga lanciata IllegalArgumentException.
     *
     */
    @Test
    public void testDeletePlaylist_nullThrowsException() {
        assertThrows(IllegalArgumentException.class, () ->
                testPlaylistController.deletePlaylist(null),
                "Dovrebbe lanciare un'eccezione per playlist null");
    }

    /**
     * Testa il tentativo di eliminare una playlist non presente in libreria.
     * Verifica che venga lanciata IllegalArgumentException e che
     * la libreria rimanga invariata.
     */
    @Test
    public void testDeletePlaylist_notInLibraryThrowsException() {
        testPlaylistController.createPlaylist("Esistente");
        Playlist notInLibrary = new Playlist("Non in libreria", false);

        assertThrows(IllegalArgumentException.class, () ->
                testPlaylistController.deletePlaylist(notInLibrary),
                "Dovrebbe lanciare un'eccezione per playlist non presente");

        assertEquals(1, testPlaylistLibrary.getPlaylists().size(),
                "La libreria deve rimanere invariata");
    }

    /**
     * Verifica che la libreria sia vuota al primo avvio della Home,
     * prima di qualsiasi operazione.
     */
    @Test
    public void testRefresh_emptyLibraryOnStartup() {
        assertTrue(testPlaylistLibrary.getPlaylists().isEmpty(),
                "La libreria deve essere vuota allo startup");
    }

    /**
     * Verifica che dopo una sequenza di creazione + eliminazione la libreria
     * rifletta esattamente lo stato atteso, ovvero quello che la ListView
     * mostrerebbe dopo l'ultimo refresh().
     */
    @Test
    public void testRefresh_afterCreateAndDelete_correctState() {
        testPlaylistController.createPlaylist("A");
        testPlaylistController.createPlaylist("B");
        Playlist a = testPlaylistLibrary.getPlaylists().get(0);

        testPlaylistController.deletePlaylist(a);

        List<Playlist> visible = testPlaylistLibrary.getPlaylists();
        assertEquals(1, visible.size(),
                "La ListView deve mostrare 1 sola playlist");
        assertEquals("B", visible.get(0).getName(),
                "La playlist rimasta deve essere 'B'");
    }
}

