/**
 * @file RenamePlaylistTest.java
 * Classe di test per la validazione della logica di business relativa
 * alla rinomina di una playlist (ID_24: Rinomina Playlist).
 *
 * <p>Verifica il corretto funzionamento di
 * {@link PlaylistController#renamePlaylist(Playlist, String)},
 * la corretta esecuzione di {@link RenamePlaylistCommand#execute()} e
 * {@link RenamePlaylistCommand#undo()}, e la gestione di tutti i casi
 * di errore previsti dagli acceptance criteria.</p>
 *
 * @see PlaylistController
 * @see RenamePlaylistCommand
 * @see PlaylistLibrary
 *
 * @author ChiaraCrisci
 */
package it.unisa.diem.sad_gruppo6.controllers;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import it.unisa.diem.sad_gruppo6.controller.business.playlist.PlaylistController;
import it.unisa.diem.sad_gruppo6.model.command.CommandManager;
import it.unisa.diem.sad_gruppo6.model.command.RenamePlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.library.PlaylistLibrary;
import it.unisa.diem.sad_gruppo6.model.library.TrackLibrary;

public class RenamePlaylistTest {

    private PlaylistLibrary playlistLibrary;
    private PlaylistController controller;
    private Playlist userPlaylist;
    private Playlist otherPlaylist;
    private Playlist autoPlaylist;

    /**
     * Setup eseguito prima di ogni test.
     * Pulisce il singleton PlaylistLibrary e ricrea le playlist di test
     * per garantire isolamento tra i test.
     */
    @BeforeEach
    public void setUp() {
        playlistLibrary = PlaylistLibrary.getInstance();
        playlistLibrary.clear();

        controller = new PlaylistController(
            TrackLibrary.getInstance(),
            playlistLibrary,
            CommandManager.getInstance()
        );

        userPlaylist  = new Playlist("Rock Anni 80", false);
        otherPlaylist = new Playlist("Jazz Moderno", false);
        autoPlaylist  = new Playlist("Auto - Pop", true);

        playlistLibrary.addPlaylist(userPlaylist);
        playlistLibrary.addPlaylist(otherPlaylist);
        playlistLibrary.addPlaylist(autoPlaylist);
    }

    /**
     * Verifica che una playlist utente venga rinominata correttamente
     * con un nome valido e non già esistente.
     */
    @Test
    public void testRenamePlaylistSuccess() {
        controller.renamePlaylist(userPlaylist, "Metal Anni 80");
        assertEquals("Metal Anni 80", userPlaylist.getName(),
            "Il nome deve essere aggiornato al nuovo valore");
    }

    /**
     * Verifica che sia possibile rinominare più volte la stessa playlist
     * senza che il nome precedente interferisca con il controllo duplicati.
     */
    @Test
    public void testRenamePlaylistMultipleTimesSuccess() {
        controller.renamePlaylist(userPlaylist, "Metal Anni 80");
        controller.renamePlaylist(userPlaylist, "Jazz Anni 80");
        assertEquals("Jazz Anni 80", userPlaylist.getName(),
            "Rinominare più volte la stessa playlist deve essere sempre consentito");
    }

    /**
     * Verifica che la rinomina con nome vuoto lanci IllegalArgumentException.
     */
    @Test
    public void testRenamePlaylistEmptyNameThrows() {
        assertThrows(IllegalArgumentException.class,
            () -> controller.renamePlaylist(userPlaylist, "   "),
            "Un nome vuoto deve lanciare IllegalArgumentException");
    }

    /**
     * Verifica che la rinomina con nome null lanci IllegalArgumentException.
     */
    @Test
    public void testRenamePlaylistNullNameThrows() {
        assertThrows(IllegalArgumentException.class,
            () -> controller.renamePlaylist(userPlaylist, null),
            "Un nome null deve lanciare IllegalArgumentException");
    }

    /**
     * Verifica che la rinomina con lo stesso nome corrente lanci IllegalArgumentException.
     */
    @Test
    public void testRenamePlaylistSameNameThrows() {
        assertThrows(IllegalArgumentException.class,
            () -> controller.renamePlaylist(userPlaylist, "Rock Anni 80"),
            "Un nome uguale al precedente deve lanciare IllegalArgumentException");
    }

    /**
     * Verifica che la rinomina con un nome già usato da un'ALTRA playlist
     * lanci IllegalArgumentException.
     */
    @Test
    public void testRenamePlaylistDuplicateNameThrows() {
        assertThrows(IllegalArgumentException.class,
            () -> controller.renamePlaylist(userPlaylist, "Jazz Moderno"),
            "Un nome già usato da un'altra playlist deve lanciare IllegalArgumentException");
    }

    /**
     * Verifica che tentare di rinominare una playlist autogenerata
     * lanci IllegalArgumentException (acceptance criteria 2).
     */
    @Test
    public void testRenameAutoGeneratedPlaylistThrows() {
        assertThrows(IllegalArgumentException.class,
            () -> controller.renamePlaylist(autoPlaylist, "Nuovo Nome"),
            "Una playlist autogenerata non può essere rinominata");
    }

    /**
     * Verifica che execute() aggiorni il nome della playlist al nuovo valore.
     */
    @Test
    public void testCommandExecuteRenamesPlaylist() {
        RenamePlaylistCommand cmd = new RenamePlaylistCommand(
            playlistLibrary, userPlaylist, "Rock Anni 80", "Heavy Metal"
        );
        cmd.execute();
        assertEquals("Heavy Metal", userPlaylist.getName(),
            "Dopo execute() il nome deve essere aggiornato al nuovo valore");
    }

    /**
     * Verifica che undo() ripristini il nome precedente della playlist.
     */
    @Test
    public void testCommandUndoRestoresOldName() {
        RenamePlaylistCommand cmd = new RenamePlaylistCommand(
            playlistLibrary, userPlaylist, "Rock Anni 80", "Heavy Metal"
        );
        cmd.execute();
        cmd.undo();
        assertEquals("Rock Anni 80", userPlaylist.getName(),
            "Dopo undo() il nome deve essere ripristinato al valore originale");
    }

    /**
     * Verifica che execute() seguito da undo() lasci la playlist nello stato iniziale.
     */
    @Test
    public void testCommandExecuteThenUndoIsIdempotent() {
        String originalName = userPlaylist.getName();
        RenamePlaylistCommand cmd = new RenamePlaylistCommand(
            playlistLibrary, userPlaylist, originalName, "Temporaneo"
        );
        cmd.execute();
        cmd.undo();
        assertEquals(originalName, userPlaylist.getName(),
            "execute() + undo() deve lasciare il nome invariato rispetto all'originale");
    }

    /**
     * Verifica che updatePlaylist() notifichi gli observer registrati,
     * confermando che la UI viene aggiornata dopo la rinomina.
     */
    @Test
    public void testUpdatePlaylistNotifiesObservers() {
        int[] callCount = {0};
        playlistLibrary.registerObserver(() -> callCount[0]++);

        playlistLibrary.updatePlaylist(userPlaylist);

        assertTrue(callCount[0] > 0,
            "updatePlaylist() deve notificare gli observer registrati");
    }
}