/**
 * @file YearPlaylistCreatorTest.java
 * @brief Classe di test per la generazione automatica di playlist per decade.
 *
 * @details Verifica il corretto comportamento di YearPlaylistCreator:
 *          - filtraggio per decade (es. 1970-1979),
 *          - restituzione di null in assenza di tracce corrispondenti,
 *          - attributo isAutoGenerated = true,
 *          - nome della playlist nel formato "XXXX-XXXX",
 *          - metodi getDecadeStart() e getDecadeName(),
 *          - costruttore con input non validi.
 *
 * @pattern Factory Method — ConcreteCreator: YearPlaylistCreator
 * @see YearPlaylistCreator
 * @see PlaylistCreator
 * @see Playlist
 * @see Track
 *
 * @author Emanuela Graziuso
 */
package it.unisa.diem.sad_gruppo6.controllers;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.factory.YearPlaylistCreator;

public class YearPlaylistCreatorTest {

    private List<Track> tracks;

    /**
     * Metodo di setup eseguito prima di ogni singolo test (@BeforeEach).
     * Crea una lista pulita di tracce di anni diversi da utilizzare come input del factory.
     * I file mp3 vengono creati come file temporanei reali per soddisfare il vincolo
     * di esistenza del path imposto dal costruttore di Track.
     */
    @BeforeEach
    public void setUp() throws Exception {
        // Creazione di file temporanei .mp3 reali (richiesto da Track.setPath)
        File f1 = File.createTempFile("track1_", ".mp3"); f1.deleteOnExit();
        File f2 = File.createTempFile("track2_", ".mp3"); f2.deleteOnExit();
        File f3 = File.createTempFile("track3_", ".mp3"); f3.deleteOnExit();
        File f4 = File.createTempFile("track4_", ".mp3"); f4.deleteOnExit();
        File f5 = File.createTempFile("track5_", ".mp3"); f5.deleteOnExit();

        tracks = new ArrayList<>();

        // Traccia 1 — anno 1975 (decade 1970-1979)
        tracks.add(new Track("Traccia A", "Autore A", 354, "Rock",  1975, f1.getAbsolutePath()));
        // Traccia 2 — anno 1979 (decade 1970-1979, estremo superiore)
        tracks.add(new Track("Traccia B", "Autore B", 255, "Pop",   1979, f2.getAbsolutePath()));
        // Traccia 3 — anno 1980 (decade 1980-1989, deve essere esclusa dalla decade 1970)
        tracks.add(new Track("Traccia C", "Autore C", 233, "Jazz",  1980, f3.getAbsolutePath()));
        // Traccia 4 — anno 2005 (decade 2000-2009)
        tracks.add(new Track("Traccia D", "Autore D", 562, "Rock",  2005, f4.getAbsolutePath()));
        // Traccia 5 — anno 1970 (decade 1970-1979, estremo inferiore)
        tracks.add(new Track("Traccia E", "Autore E", 301, "Pop",   1970, f5.getAbsolutePath()));
    }

    /**
     * Verifica che il creator produca una playlist con tutte e sole le tracce
     * appartenenti alla decade calcolata dall'anno passato al costruttore.
     * Passando 1975 ci si aspetta la decade 1970-1979: tracce A, B, E → 3 tracce.
     */
    @Test
    public void testCreatePlaylistConDecadeEsistente() {
        YearPlaylistCreator creator = new YearPlaylistCreator(1975);
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist, "La playlist non dovrebbe essere null se esistono tracce della decade");
        assertEquals(3, playlist.getTracks().size(),
                "Dovrebbero essere presenti 3 tracce nella decade 1970-1979");
    }

    /**
     * Verifica che il nome della playlist sia nel formato corretto "XXXX-XXXX".
     * Passando 2005 il nome atteso è "2000-2009".
     */
    @Test
    public void testNomePlaylistFormatoDecade() {
        YearPlaylistCreator creator = new YearPlaylistCreator(2005);
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist);
        assertEquals("2000-2009", playlist.getName(),
                "Il nome della playlist deve essere nel formato 'XXXX-XXXX'");
    }

    /**
     * Verifica che la playlist prodotta abbia il flag isAutoGenerated = true,
     * come richiesto dal pattern Factory Method per le playlist automatiche.
     */
    @Test
    public void testPlaylistIsAutoGenerated() {
        YearPlaylistCreator creator = new YearPlaylistCreator(1975);
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist);
        assertTrue(playlist.isAutoGenerated(),
                "La playlist generata automaticamente deve avere isAutoGenerated = true");
    }

    /**
     * Verifica che anni diversi ma appartenenti alla stessa decade producano
     * lo stesso risultato (stessa decade calcolata).
     * 1970 e 1979 devono entrambi produrre la decade "1970-1979".
     */
    @Test
    public void testAnniDiversiStessaDecadeProduconoStessaPlaylist() {
        YearPlaylistCreator creator1970 = new YearPlaylistCreator(1970);
        YearPlaylistCreator creator1979 = new YearPlaylistCreator(1979);

        Playlist p1 = creator1970.createPlaylist(tracks);
        Playlist p2 = creator1979.createPlaylist(tracks);

        assertNotNull(p1);
        assertNotNull(p2);
        assertEquals(p1.getTracks().size(), p2.getTracks().size(),
                "Anni diversi della stessa decade devono produrre playlist con lo stesso numero di tracce");
        assertEquals(p1.getName(), p2.getName(),
                "La decade calcolata deve essere identica per anni appartenenti allo stesso decennio");
    }

    /**
     * Verifica che la playlist contenga soltanto le tracce appartenenti alla decade
     * e che le tracce di altri anni siano escluse.
     */
    @Test
    public void testPlaylistContieneEsclusivamenteTracceDellaDecade() {
        YearPlaylistCreator creator = new YearPlaylistCreator(1975); // decade 1970-1979
        Playlist playlist = creator.createPlaylist(tracks);

        assertNotNull(playlist);
        for (Track t : playlist.getTracks()) {
            assertTrue(t.getYear() >= 1970 && t.getYear() <= 1979,
                    "Tutte le tracce devono avere anno compreso tra 1970 e 1979, trovato: "
                    + t.getYear());
        }
    }

    /**
     * Verifica che getDecadeStart() restituisca l'anno di inizio della decade
     * calcolato a partire dall'anno passato al costruttore.
     * Passando 1975 il decadeStart atteso è 1970.
     */
    @Test
    public void testGetDecadeStartRestituisceValoreCorretto() {
        YearPlaylistCreator creator = new YearPlaylistCreator(1975);
        assertEquals(1970, creator.getDecadeStart(),
                "getDecadeStart() deve restituire l'inizio della decade (1970 per 1975)");
    }

    /**
     * Verifica che getDecadeName() restituisca la stringa nel formato "XXXX-XXXX".
     */
    @Test
    public void testGetDecadeNameRestituisceFormatoCorretto() {
        YearPlaylistCreator creator = new YearPlaylistCreator(2005);
        assertEquals("2000-2009", creator.getDecadeName(),
                "getDecadeName() deve restituire '2000-2009' per l'anno 2005");
    }

    /**
     * Verifica che createPlaylist() funzioni correttamente su una lista vuota,
     * restituendo null senza sollevare eccezioni.
     */
    @Test
    public void testCreatePlaylistConListaVuotaRestituisceNull() {
        YearPlaylistCreator creator = new YearPlaylistCreator(1975);
        Playlist playlist = creator.createPlaylist(new ArrayList<>());

        assertNull(playlist,
                "Con una lista di tracce vuota il creator deve restituire null");
    }

    /**
     * Verifica che il creator restituisca null quando nessuna traccia
     * della libreria appartiene alla decade specificata.
     */
    @Test
    public void testCreatePlaylistRestituisceNullSeNessunaTrAcciaDellaDecade() {
        YearPlaylistCreator creator = new YearPlaylistCreator(1900); // decade 1900-1909
        Playlist playlist = creator.createPlaylist(tracks);

        assertNull(playlist,
                "Se nessuna traccia appartiene alla decade, il creator deve restituire null");
    }

    /**
     * Verifica che il costruttore lanci IllegalArgumentException
     * quando viene passato un anno <= 0.
     */
    @Test
    public void testCostruttoreConAnnoZeroLanciaEccezione() {
        assertThrows(IllegalArgumentException.class,
                () -> new YearPlaylistCreator(0),
                "Il costruttore deve lanciare IllegalArgumentException per anno = 0");
    }

    /**
     * Verifica che il costruttore lanci IllegalArgumentException
     * quando viene passato un anno negativo.
     */
    @Test
    public void testCostruttoreConAnnoNegativoLanciaEccezione() {
        assertThrows(IllegalArgumentException.class,
                () -> new YearPlaylistCreator(-1990),
                "Il costruttore deve lanciare IllegalArgumentException per anno negativo");
    }
}