/**
 * @file EditTrackCommand.java
 *
 * Classe concreta che implementa l'interfaccia AppCommand per incapsulare
 * l'azione di modifica dei metadati di una traccia già presente nella
 * TrackLibrary.
 *
 * @pattern Command
 * @see AppCommand
 * @see TrackLibrary
 * @see Track
 * @author ChiaraCrisci
 */
package it.unisa.diem.sad_gruppo6.model.command;

import java.io.FileNotFoundException;
import java.util.List;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.library.TrackLibrary;
import it.unisa.diem.sad_gruppo6.model.library.PlaylistLibrary;
import it.unisa.diem.sad_gruppo6.model.playback.states.PlaybackState;
import it.unisa.diem.sad_gruppo6.model.playback.states.PausedState;
import it.unisa.diem.sad_gruppo6.model.service.PlaybackService;

public class EditTrackCommand implements AppCommand
{
    private final TrackLibrary library;
    private final PlaylistLibrary playlistLibrary;
    private final Track oldTrack;
    private final Track updatedTrack;

    /**
     * Costruttore del comando EditTrackCommand.
     *
     * @param oldTrack     la traccia originale da sostituire.
     * @param updatedTrack la traccia con i nuovi metadati.
     */
    public EditTrackCommand(Track oldTrack, Track updatedTrack)
    {
        // Utilizza il Singleton strutturato da Luigi
        this.library      = TrackLibrary.getInstance();
        this.playlistLibrary = PlaylistLibrary.getInstance();
        this.oldTrack     = oldTrack;
        this.updatedTrack = updatedTrack;
    }

    @Override
    public void execute()
    {
        library.updateTrack(oldTrack, updatedTrack);
        List<Playlist> allPlaylists = playlistLibrary.getPlaylists();
    
        for (Playlist p : allPlaylists) {
            if (p.isAutoGenerated()) {
                continue;
            }
            List<Track> tracksInPlaylist = p.getTracks();
            
            // Se la playlist contiene la vecchia traccia
            if (tracksInPlaylist.contains(oldTrack)) {
                // Sostituisci l'oggetto vecchio con quello nuovo
                int index = tracksInPlaylist.indexOf(oldTrack);
                tracksInPlaylist.set(index, updatedTrack);
            }
        }
        
        playlistLibrary.updatePlaylist(null);

        PlaybackState playbackState = PlaybackState.getInstance();
        if (playbackState.getCurrentTrack() == oldTrack) {
            playbackState.setCurrentTrack(updatedTrack);
        }
    }

    @Override
    public void undo() {
        library.updateTrack(updatedTrack, oldTrack);
        List<Playlist> allPlaylists = playlistLibrary.getPlaylists();

        for (Playlist p : allPlaylists) {
            if (p.isAutoGenerated()) continue;
            List<Track> tracksInPlaylist = p.getTracks();
            if (tracksInPlaylist.contains(updatedTrack)) {
                int index = tracksInPlaylist.indexOf(updatedTrack);
                tracksInPlaylist.set(index, oldTrack);
            }
        }

        playlistLibrary.updatePlaylist(null);

        PlaybackState playbackState = PlaybackState.getInstance();
        if (playbackState.getCurrentTrack() == updatedTrack) {
            playbackState.setCurrentTrack(oldTrack);
        }
    }
    }