/**
 * @file EditTrackCommand.java
 *
 * Classe concreta che implementa l'interfaccia AppCommand per incapsulare
 * l'azione di modifica dei metadati di una traccia già presente nella
 * TrackLibrary.
 *
 * @pattern Command
 * @see AppCommand
 * @see TrackLibrary
 * @see Track
 * @author ChiaraCrisci
 */
package it.unisa.diem.sad_gruppo6.model.command;

import java.io.FileNotFoundException;
import java.util.List;

import it.unisa.diem.sad_gruppo6.controller.business.playlist.PlaylistController;
import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.domain.Tag;
import it.unisa.diem.sad_gruppo6.model.library.TrackLibrary;
import it.unisa.diem.sad_gruppo6.model.library.PlaylistLibrary;
import it.unisa.diem.sad_gruppo6.model.playback.states.PlaybackState;
import it.unisa.diem.sad_gruppo6.model.playback.states.PausedState;
import it.unisa.diem.sad_gruppo6.model.service.PlaybackService;

public class EditTrackCommand implements AppCommand
{
    private final TrackLibrary library;
    private final PlaylistLibrary playlistLibrary;
    private final PlaylistController playlistController;
    private final Track oldTrack;
    private final Track updatedTrack;

    /**
     * Costruttore del comando EditTrackCommand.
     *
     * @param oldTrack     la traccia originale da sostituire.
     * @param updatedTrack la traccia con i nuovi metadati.
     */
    public EditTrackCommand(Track oldTrack, Track updatedTrack)
    {
        // Utilizza il Singleton strutturato da Luigi
        this.library      = TrackLibrary.getInstance();
        this.playlistLibrary = PlaylistLibrary.getInstance();
        this.playlistController = new PlaylistController(this.library, this.playlistLibrary, CommandManager.getInstance());
        this.oldTrack     = oldTrack;
        this.updatedTrack = updatedTrack;
    }

    @Override
    public void execute()
    {
        library.updateTrack(oldTrack, updatedTrack);
        List<Playlist> allPlaylists = playlistLibrary.getPlaylists();
    
        for (Playlist p : allPlaylists) {
            if (p.isAutoGenerated()) {
                continue;
            }
            List<Track> tracksInPlaylist = p.getTracks();
            
            // Se la playlist contiene la vecchia traccia
            if (tracksInPlaylist.contains(oldTrack)) {
                // Sostituisci l'oggetto vecchio con quello nuovo
                int index = tracksInPlaylist.indexOf(oldTrack);
                tracksInPlaylist.set(index, updatedTrack);
            }
        }

        syncAutoPlaylists(oldTrack, updatedTrack);
        
        playlistLibrary.updatePlaylist(null);

        PlaybackState playbackState = PlaybackState.getInstance();
        if (playbackState.getCurrentTrack() == oldTrack) {
            playbackState.setCurrentTrack(updatedTrack);
        }
    }

    @Override
    public void undo() {
        library.updateTrack(updatedTrack, oldTrack);
        List<Playlist> allPlaylists = playlistLibrary.getPlaylists();

        for (Playlist p : allPlaylists) {
            if (p.isAutoGenerated()) continue;
            List<Track> tracksInPlaylist = p.getTracks();
            if (tracksInPlaylist.contains(updatedTrack)) {
                int index = tracksInPlaylist.indexOf(updatedTrack);
                tracksInPlaylist.set(index, oldTrack);
            }
        }

        syncAutoPlaylists(updatedTrack, oldTrack);

        playlistLibrary.updatePlaylist(null);

        PlaybackState playbackState = PlaybackState.getInstance();
        if (playbackState.getCurrentTrack() == updatedTrack) {
            playbackState.setCurrentTrack(oldTrack);
        }
    }


    /**
     * Ricalcola le playlist automatiche (genere, decade, EXPLICIT, NEW_RELEASE)
     * dopo che 'from' è stata sostituita da 'to' nella TrackLibrary.
     * @details Centralizza qui la logica già usata da TrackController#editTrack,
     * in modo che venga eseguita simmetricamente sia in execute() che in undo():
     * crea/aggiorna le playlist automatiche relative ai metadati di 'to' e,
     * se genere o decade sono cambiati rispetto a 'from', rimuove le
     * corrispondenti playlist automatiche di 'from' qualora rimangano vuote.
     *
     * @param from la traccia precedente (prima della sostituzione).
     * @param to   la traccia subentrante (dopo la sostituzione).
     */
    private void syncAutoPlaylists(Track from, Track to)
    {
        String fromGenre = from.getGenre();
        String toGenre = to.getGenre();
        int fromYear = from.getYear();
        int toYear = to.getYear();

        if (!fromGenre.equalsIgnoreCase(toGenre)) {
            playlistController.createAutoPlaylist(fromGenre);
            playlistController.removeGenrePlaylistIfEmpty(fromGenre);
        }

        playlistController.createAutoPlaylist(toGenre);
        playlistController.createAutoPlaylist(Tag.Explicit);
        playlistController.removeTagPlaylistIfEmpty(Tag.Explicit);
        playlistController.createAutoPlaylist(Tag.NewRelease);
        playlistController.removeTagPlaylistIfEmpty(Tag.NewRelease);

        if (fromYear != toYear) {
            playlistController.createAutoPlaylist(fromYear);
            playlistController.removeYearPlaylistIfEmpty(fromYear);
        }
        playlistController.createAutoPlaylist(toYear);
    }
    }