/**
 * @file TagPlaylistCreator.java
 * @brief ConcreteCreator del pattern Factory Method per la generazione automatica
 *        di playlist filtrate per tag visivo (es. FAVOURITE, EXPLICIT, NEW_RELEASE).
 *
 * @details Estende PlaylistCreator e implementa createPlaylist(List)
 *          selezionando dalla TrackLibrary tutte le tracce il cui TagSet contiene
 *          il tag ricevuto nel costruttore.
 *          La playlist prodotta ha isAutoGenerated = true e come nome
 *          il nome del tag (es. "FAVOURITE").
 *          Restituisce null se nessuna traccia possiede il tag, così il chiamante
 *          può decidere di non creare né mantenere la playlist.
 *
 * @pattern Factory Method
 * @see PlaylistCreator
 * @see Playlist
 * @see it.unisa.diem.sad_gruppo6.model.domain.Tag
 * @see it.unisa.diem.sad_gruppo6.model.domain.TagSet
 *
 * @author ChiaraCrisci
 */
package it.unisa.diem.sad_gruppo6.model.factory;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Tag;
import it.unisa.diem.sad_gruppo6.model.domain.Track;

import java.util.List;

public class TagPlaylistCreator extends PlaylistCreator {

    /** Il tag visivo usato come criterio di filtraggio. */
    private final Tag tag;

    /**
     * @brief Costruttore del TagPlaylistCreator.
     *
     * @param tag Il tag in base al quale filtrare le tracce. Non deve essere null.
     * @throws IllegalArgumentException Se il tag è null.
     */
    public TagPlaylistCreator(Tag tag) {
        if (tag == null) {
            throw new IllegalArgumentException("Il tag non può essere null.");
        }
        this.tag = tag;
    }

    /**
     * @brief Crea una playlist automatica con tutte le tracce che possiedono il tag specificato.
     *
     * @details Itera su tracks e aggiunge alla playlist ogni traccia il cui TagSet
     *          contiene tag (verificato tramite Track#getTagSet() e TagSet#hasTag(Tag)).
     *          Il nome della playlist è uguale al nome del tag (Tag#name()) e
     *          isAutoGenerated è impostato a true.
     *          Restituisce null se nessuna traccia possiede il tag, così il chiamante
     *          può decidere di non creare né mantenere la playlist.
     *
     * @param tracks La lista completa di tracce della TrackLibrary.
     * @return Una Playlist con isAutoGenerated = true e nome uguale al nome del tag,
     *         oppure null se nessuna traccia possiede il tag.
     */
    @Override
    public Playlist createPlaylist(List<Track> tracks) {
        Playlist playlist = new Playlist(tag.name(), true);

        for (Track t : tracks) {
            if (t.getTagSet().hasTag(tag)) {
                playlist.addTrack(t);
            }
        }
        
        if (playlist.getTracks().isEmpty()) {
            return null;
        }

        return playlist;
    }

    /**
     * @brief Restituisce il tag associato a questo creator.
     * @return Il tag usato come criterio.
     */
    public Tag getTag() {
        return tag;
    }
}