/**
 * @file YearPlaylistCreator.java
 * @brief ConcreteCreator del pattern Factory Method per la generazione automatica
 *        di playlist filtrate per anno di pubblicazione.
 *
 * @details Estende PlaylistCreator e implementa createPlaylist(List)
 *          selezionando dalla TrackLibrary tutte le tracce il cui anno corrisponde
 *          a quello ricevuto nel costruttore.
 *          La playlist prodotta ha isAutoGenerated = true e come nome
 *          l'anno stesso come stringa (es. "2023").
 *          Restituisce null se nessuna traccia appartiene all'anno,
 *          così il chiamante può decidere di non creare né mantenere la playlist.
 *
 * @pattern Factory Method
 * @see PlaylistCreator
 * @see Playlist
 *
 * @author EmanuelaGraziuso
 */
package it.unisa.diem.sad_gruppo6.model.factory;

import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;

import java.util.List;

public class YearPlaylistCreator extends PlaylistCreator {

    private final int decadeStart;

    /**
     * @brief Costruttore del YearPlaylistCreator.
     *
     * @param year Un qualsiasi anno appartenente alla decade desiderata.
     *             La decade viene calcolata automaticamente (es. 1993 → 1990-1999).
     *             Deve essere un valore positivo.
     * @throws IllegalArgumentException Se l'anno è <= 0.
     */
    public YearPlaylistCreator(int year) {
        if (year <= 0) {
            throw new IllegalArgumentException("L'anno non può essere <= 0.");
        }
        this.decadeStart = (year / 10) * 10;
    }

    /**
     * @brief Crea una playlist automatica con tutte le tracce della decade specificata.
     *
     * @details Itera su tracks e aggiunge alla playlist ogni traccia il cui
     *          anno è compreso nell'intervallo [decadeStart, decadeStart + 9].
     *          Il nome della playlist è nel formato "XXXX-XXXX" (es. "2020-2029").
     *          Restituisce null se nessuna traccia appartiene alla decade.
     *
     * @param tracks La lista completa di tracce della TrackLibrary.
     * @return Una Playlist con isAutoGenerated = true e nome del formato decade,
     *           oppure null se non ci sono tracce della decade.
     */
    @Override
    public Playlist createPlaylist(List<Track> tracks) {
        String name = decadeStart + "-" + (decadeStart + 9);
        Playlist playlist = new Playlist(name, true);

        for (Track t : tracks) {
            if (t.getYear() >= decadeStart && t.getYear() <= decadeStart + 9) {
                playlist.addTrack(t);
            }
        }

        if (playlist.getTracks().isEmpty()) {
            return null;
        }

        return playlist;
    }

    /**
     * @brief Restituisce l'anno iniziale della decade.
     * @return L'anno di inizio della decade (es. 2020 per "2020-2029").
     */
    public int getDecadeStart() {
        return decadeStart;
    }

    /**
     * @brief Restituisce il nome della decade nel formato "XXXX-XXXX".
     * @return La stringa usata come nome della playlist (es. "2020-2029").
     */
    public String getDecadeName() {
        return decadeStart + "-" + (decadeStart + 9);
    }
}