/**
 * @file Playlist.java
 * Classe di definizione di un oggetto di tipo 'Playlist'.
 * 
 * @author LuigiAutorino
 */

package it.unisa.diem.sad_gruppo6.model.domain;

import java.util.List;
import java.util.ArrayList;

public class Playlist {

    // Attributi
    private String name;
    private List<Track> tracks;
    private boolean isAutoGenerated;

    /**
     * Costruttore classe 'Playlist'.
     * @param name Il nome della playlist.
     * @param isAutoGenerated Booleano che indica se la playlist è generata automaticamente (true) o dall'utente (false).
     */
    public Playlist(String name, boolean isAutoGenerated) {
        this.name = name;
        this.isAutoGenerated = isAutoGenerated;
        this.tracks = new ArrayList<>();
    }

    // Getter e Setter

    /**
     * Getter del nome della playlist.
     * * @return Il nome della playlist.
     */
    public String getName() {
        return name;
    }

    /**
     * Setter del nome della playlist, con controllo di validità sull'input.
     * * @param name Il nome da assegnare alla playlist.
     * @throws IllegalArgumentException Se il nome è null o vuoto.
     */
    public void setName(String name) {
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException("Playlist name can't be empty.");
        }
        this.name = name;
    }

    /**
     * Getter della lista delle tracce presenti nella playlist.
     * * @return La lista di oggetti 'Track' contenuti nella playlist.
     */
    public List<Track> getTracks() {
        return tracks;
    }

    /**
     * Restituisce il numero totale di tracce attualmente presenti nella playlist.
     * Questo metodo è utile per fornire metadati all'interfaccia grafica (View) 
     * senza dover esporre direttamente o scorrere l'intera collezione di tracce.
     *
     * @return Il numero intero di tracce contenute nella playlist. Se la lista è vuota, restituisce 0.
     */
    public int getNumTracks() {
        if (this.tracks != null) {
            return this.tracks.size();
        }
        return 0;
    }

    /**
     * Verifica se la playlist è stata generata in automatico dal sistema.
     * * @return true se la playlist è autogenerata, false altrimenti.
     */
    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    /* // Metodi di gestione delle tracce
    
    /**
     * Aggiunge una traccia alla playlist solo se non è già presente.
     * Il controllo dei duplicati si basa sul metodo equals() della classe 'Track', 
     * che confronta titolo e autore.
     * 
     * * @param t La traccia da aggiungere.
     */
    
    public void addTrack(Track t) {
        if (!tracks.contains(t)) {
            tracks.add(t);
        }
    }
    

    /**
     * Rimuove una traccia dalla playlist.
     * * @param t La traccia da rimuovere.
     * 
     * @throws IllegalArgumentException Se la traccia da rimuovere non è presente nella playlist.
     */
    
    public void removeTrack(Track t) {
        if (!tracks.contains(t)) 
            throw new IllegalArgumentException("La traccia non è presente nella playlist.");
        
        tracks.remove(t);
    }
    

    /**
     * @brief Sposta una traccia in una nuova posizione all'interno della playlist.
     * @param t La traccia da spostare.
     * @param newIndex Il nuovo indice in cui inserire la traccia.
     * @throws IllegalArgumentException Se la traccia non esiste o l'indice non è valido.
     */
    public void reorder(Track t, int newIndex) {
        int oldIndex = tracks.indexOf(t);
        
        if (oldIndex == -1) {
            throw new IllegalArgumentException("La traccia non è presente in questa playlist.");
        }
        if (newIndex < 0 || newIndex > tracks.size() - 1) {
            throw new IllegalArgumentException("Indice di destinazione non valido.");
        }
        
        tracks.remove(oldIndex);
        tracks.add(newIndex, t);
    }

    /**
     * Restituisce la rappresentazione testuale della playlist.
     */
    @Override
    public String toString() {
        return this.getName();
    }
    
}
