package it.unisa.diem.sad_gruppo6.models;

//import java.util.List;
//import java.util.ArrayList;

public class Playlist {
    // Attributi
    private String name;
    //private List<Track> tracks;
    private boolean isAutoGenerated;

    // Metodo Costruttore
    public Playlist(String name, boolean isAutoGenerated) {
        this.name = name;
        this.isAutoGenerated = isAutoGenerated;
        //this.tracks = new ArrayList<>();
    }

    // Getter e Setter
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /*public List<Track> getTracks() {
        return tracks;
    }
    */

    // Metodi utili
    public boolean isAutoGenerated() {
        return isAutoGenerated;
    }

    /*Altri metodi
    public void addTrack(Track t) {

    }

    public void removeTrack(Track t) {

    }

    public void reorder(Track t, int newIndex) {

    }
    */
}
