/**
 * @file PlaylistController.java
 * Classe controller che gestisce la logica di business relativa alle playlist.
 * Si occupa della validazione dei dati e di orchestrare le operazioni tra i modelli 
 * (PlaylistLibrary, TrackLibrary) e il gestore dei comandi (CommandManager).
 * * @author LuigiAutorino, ChiaraCrisci
 */
package it.unisa.diem.sad_gruppo6.controller.business.playlist;

import it.unisa.diem.sad_gruppo6.model.command.AddTrackToPlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.command.AppCommand;
import it.unisa.diem.sad_gruppo6.model.command.CommandManager;
import it.unisa.diem.sad_gruppo6.model.command.CreatePlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.command.RenamePlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.command.RemoveTrackFromPlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.library.PlaylistLibrary;
import it.unisa.diem.sad_gruppo6.model.library.TrackLibrary;

public class PlaylistController {

    // Attributi
    private TrackLibrary trackLibrary;
    private PlaylistLibrary playlistLibrary;
    private CommandManager commandManager;

    /**
     * Costruttore completo della classe 'PlaylistController'.
     * * @param trackLibrary La libreria generale delle tracce.
     * @param playlistLibrary La libreria delle playlist dell'utente.
     * @param commandManager Il gestore dei comandi per abilitare le funzionalità di Undo.
     */
    public PlaylistController (TrackLibrary trackLibrary, PlaylistLibrary playlistLibrary, CommandManager commandManager) {
        this.trackLibrary = trackLibrary;
        this.playlistLibrary = playlistLibrary;
        this.commandManager = commandManager;
    }

    /**
     * Crea una nuova playlist vuota (non autogenerata) e la aggiunge alla libreria tramite CommandManager.
     * * @param name Il nome desiderato per la nuova playlist.
     * @throws IllegalArgumentException Se il nome è null, vuoto, o se esiste già una playlist con lo stesso nome.
     */
    public void createPlaylist(String name) throws IllegalArgumentException {
        // Controllo su nome vuoto
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Il nome della playlist non può essere vuoto.");
        }

        // Controllo su unicità nome
        if (playlistLibrary.containsPlaylistName(name)) {
            throw new IllegalArgumentException("Esiste già una playlist con questo nome.");
        }

        Playlist newPlaylist = new Playlist(name.trim(), false);
        AppCommand command = new CreatePlaylistCommand(playlistLibrary, newPlaylist);
        commandManager.execute(command);
    }

    /* Metodi da implementare

    /*
    /**
     * Elimina una playlist esistente dalla libreria.
     * Solo le playlist non autogenerate dal sistema possono essere eliminate.
     * 
     * @param p La playlist da eliminare.
     * @throws IllegalArgumentException Se la playlist è autogenerata.
     */
    
    public void deletePlaylist(Playlist p) {
        if (p == null) throw new IllegalArgumentException("La playlist non può essere null.");

        if(p.isAutoGenerated()){
            throw new IllegalArgumentException("Le playlist generate automaticamente non possono essere eliminate");
        }

        if (!playlistLibrary.getPlaylists().contains(p)) {
        throw new IllegalArgumentException("La playlist non è presente nella libreria.");
        }
        playlistLibrary.removePlaylist(p); 
    }
    

    /*
     * Rinomina una playlist esistente verificando che il nuovo nome sia valido,
     * non uguale al precedente, non già utilizzato da un'altra playlist e che
     * la playlist non sia autogenerata dal sistema.
     *
     * @param p       La playlist da rinominare.
     * @param newName Il nuovo nome da assegnare.
     * @throws IllegalArgumentException Se il nuovo nome è vuoto, uguale al precedente,
     *                                  già esistente nella libreria, o se la playlist
     *                                  è autogenerata e non modificabile.
     */
    public void renamePlaylist(Playlist p, String newName) throws IllegalArgumentException {
        // Controllo: la playlist non deve essere autogenerata
        if (p.isAutoGenerated()) {
            throw new IllegalArgumentException("Le playlist generate automaticamente non possono essere rinominate.");
        }

        // Controllo: nome non vuoto
        if (newName == null || newName.trim().isEmpty()) {
            throw new IllegalArgumentException("Il nuovo nome non può essere vuoto.");
        }

        // Controllo: nome diverso dal precedente
        if (newName.trim().equalsIgnoreCase(p.getName())) {
            throw new IllegalArgumentException("Il nuovo nome è uguale a quello attuale.");
        }

        // Controllo: nome non già usato da un'altra playlist
        for (Playlist existing : playlistLibrary.getPlaylists()) {
        if (existing != p && existing.getName().equalsIgnoreCase(newName.trim())) {
            throw new IllegalArgumentException("Esiste già una playlist con questo nome.");
        }
}

        AppCommand command = new RenamePlaylistCommand(playlistLibrary, p, p.getName(), newName.trim());
        commandManager.execute(command);
    }

    
    /**
     * Aggiunge una traccia a una specifica playlist, verificando che non sia già presente.
     * La playlist non ammette duplicati per la medesima traccia.
     * 
     * @param t La traccia da aggiungere.
     * @param p La playlist di destinazione.
     * 
     * @throws IllegalArgumentException Se la traccia è già presente nella playlist.
     * 
     */
    
    public void addTrackToPlaylist(Track t, Playlist p) {
        if(p.getTracks().contains(t)) {
            throw new IllegalArgumentException("La traccia è già presente nella playlist.");
        }
        AppCommand command = new AddTrackToPlaylistCommand(p, t);
        commandManager.execute(command);
    }
    

    
    /**
     * Rimuove una traccia da una specifica playlist.
     * @param t La traccia da rimuovere.
     * @param p La playlist da cui rimuovere la traccia.
     * 
     */

    public void removeTrackFromPlaylist(Track t, Playlist p) {
        if (t == null) {
        throw new IllegalArgumentException("La traccia non può essere null.");
        }
        if (!p.getTracks().contains(t)) {
            throw new IllegalArgumentException("La traccia non è presente nella playlist.");
        }
        AppCommand command = new RemoveTrackFromPlaylistCommand(p, t);
        commandManager.execute(command);
        playlistLibrary.updatePlaylist(p); 
    }

    /*
    /**
     * Cambia la posizione di una traccia all'interno di una playlist.
     * * @param t La traccia da spostare.
     * @param p La playlist che contiene la traccia.
     * @param newIndex Il nuovo indice in cui posizionare la traccia.
     */
    /*
    public void reorderTrack(Track t, Playlist p, int newIndex) {

    }
    */

    /*
    /**
     * Crea una playlist autogenerata basata su uno specifico Tag.
     * * @param tag Il tag da utilizzare come filtro.
     */
    /*
    public void createAutoPlaylist(Tag tag) {

    }
    */

    /*
    /**
     * Crea una playlist autogenerata basata su uno specifico genere musicale.
     * * @param genre Il genere musicale da utilizzare come filtro.
     */
    /*
    public void createAutoPlaylist(String genre) {
        
    }
    */

    /*
    /**
     * Crea una playlist autogenerata basata su uno specifico anno di pubblicazione.
     * * @param year L'anno da utilizzare come filtro.
     */
    /*
    public void createAutoPlaylist(int year) {
        
    }
    */
}
