/**
 * @file PlaylistController.java
 * Classe controller che gestisce la logica di business relativa alle playlist.
 * Si occupa della validazione dei dati e di orchestrare le operazioni tra i modelli 
 * (PlaylistLibrary, TrackLibrary) e il gestore dei comandi (CommandManager).
 * * @author LuigiAutorino, ChiaraCrisci
 */
package it.unisa.diem.sad_gruppo6.controller.business.playlist;

import it.unisa.diem.sad_gruppo6.model.command.AddTrackToPlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.command.AppCommand;
import it.unisa.diem.sad_gruppo6.model.command.CommandManager;
import it.unisa.diem.sad_gruppo6.model.command.CreatePlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.command.RenamePlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.command.ReorderTrackCommand;
import it.unisa.diem.sad_gruppo6.model.command.RemoveTrackFromPlaylistCommand;
import it.unisa.diem.sad_gruppo6.model.domain.Playlist;
import it.unisa.diem.sad_gruppo6.model.domain.Track;
import it.unisa.diem.sad_gruppo6.model.library.PlaylistLibrary;
import it.unisa.diem.sad_gruppo6.model.library.TrackLibrary;
import it.unisa.diem.sad_gruppo6.model.factory.GenrePlaylistCreator;
import it.unisa.diem.sad_gruppo6.model.factory.YearPlaylistCreator;
import it.unisa.diem.sad_gruppo6.model.domain.Tag;
import it.unisa.diem.sad_gruppo6.model.factory.TagPlaylistCreator;
import it.unisa.diem.sad_gruppo6.model.factory.MostPlayedPlaylistCreator;

public class PlaylistController {

    // Attributi
    private TrackLibrary trackLibrary;
    private PlaylistLibrary playlistLibrary;
    private CommandManager commandManager;

    /**
     * Costruttore completo della classe 'PlaylistController'.
     * * @param trackLibrary La libreria generale delle tracce.
     * @param playlistLibrary La libreria delle playlist dell'utente.
     * @param commandManager Il gestore dei comandi per abilitare le funzionalità di Undo.
     */
    public PlaylistController (TrackLibrary trackLibrary, PlaylistLibrary playlistLibrary, CommandManager commandManager) {
        this.trackLibrary = trackLibrary;
        this.playlistLibrary = playlistLibrary;
        this.commandManager = commandManager;
    }

    /**
     * Crea una nuova playlist vuota (non autogenerata) e la aggiunge alla libreria tramite CommandManager.
     * * @param name Il nome desiderato per la nuova playlist.
     * @throws IllegalArgumentException Se il nome è null, vuoto, o se esiste già una playlist con lo stesso nome.
     */
    public void createPlaylist(String name) throws IllegalArgumentException {
        // Controllo su nome vuoto
        if (name == null || name.trim().isEmpty()) {
            throw new IllegalArgumentException("Playlist name can't be empty.");
        }

        // Controllo su unicità nome
        String trimmedName = name.trim();
        for (Playlist p : playlistLibrary.getPlaylists()) {
            if (p.getName().equals(trimmedName)) {
                throw new IllegalArgumentException("Playlist name is already used.");
            }
        }

        Playlist newPlaylist = new Playlist(trimmedName, false);
        AppCommand command = new CreatePlaylistCommand(playlistLibrary, newPlaylist);
        commandManager.execute(command);
    }

    /**
     * Elimina una playlist esistente dalla libreria.
     * Solo le playlist non autogenerate dal sistema possono essere eliminate.
     * 
     * @param p La playlist da eliminare.
     * @throws IllegalArgumentException Se la playlist è autogenerata.
     */
    
    public void deletePlaylist(Playlist p) {
        if (p == null) throw new IllegalArgumentException("Playlist can't be null.");

        if(p.isAutoGenerated()){
            throw new IllegalArgumentException("Automatic Playlists can't be deleted.");
        }

        if (!playlistLibrary.getPlaylists().contains(p)) {
        throw new IllegalArgumentException("Playlist doesn't exist.");
        }
        playlistLibrary.removePlaylist(p); 
    }
    

    /*
     * Rinomina una playlist esistente verificando che il nuovo nome sia valido,
     * non uguale al precedente, non già utilizzato da un'altra playlist e che
     * la playlist non sia autogenerata dal sistema.
     *
     * @param p       La playlist da rinominare.
     * @param newName Il nuovo nome da assegnare.
     * @throws IllegalArgumentException Se il nuovo nome è vuoto, uguale al precedente, 
     * già esistente nella libreria, o se la playlist è autogenerata e non modificabile.
     */
    public void renamePlaylist(Playlist p, String newName) throws IllegalArgumentException {
        // Controllo: la playlist non deve essere autogenerata
        if (p.isAutoGenerated()) {
            throw new IllegalArgumentException("Automatic Playlists can't be renamed.");
        }

        // Controllo: nome non vuoto
        if (newName == null || newName.trim().isEmpty()) {
            throw new IllegalArgumentException("New name can't be empty.");
        }

        String trimmedNewName = newName.trim();
        // Controllo: nome diverso dal precedente
        if (trimmedNewName.equals(p.getName())) {
            throw new IllegalArgumentException("New name is equal to the actual one.");
        }

        // Controllo: nome non già usato da un'altra playlist (Case-Sensitive)
        for (Playlist existing : playlistLibrary.getPlaylists()) {
            if (existing != p && existing.getName().equals(trimmedNewName)) {
                throw new IllegalArgumentException("Playlist name already used.");
            }
        }

        AppCommand command = new RenamePlaylistCommand(playlistLibrary, p, p.getName(), trimmedNewName);
        commandManager.execute(command);
    }

    
    /**
     * Aggiunge una traccia a una specifica playlist, verificando che non sia già presente.
     * La playlist non ammette duplicati per la medesima traccia.
     * 
     * @param t La traccia da aggiungere.
     * @param p La playlist di destinazione.
     * 
     * @throws IllegalArgumentException Se la traccia è già presente nella playlist.
     * 
     */
    
    public void addTrackToPlaylist(Track t, Playlist p) {
        if(p.getTracks().contains(t)) {
            throw new IllegalArgumentException("This track is already in the playlist.");
        }
        AppCommand command = new AddTrackToPlaylistCommand(p, t);
        commandManager.execute(command);
    }
    

    
    /**
     * Rimuove una traccia da una specifica playlist.
     * @param t La traccia da rimuovere.
     * @param p La playlist da cui rimuovere la traccia.
     * 
     */

    public void removeTrackFromPlaylist(Track t, Playlist p) {
        if (t == null) {
        throw new IllegalArgumentException("Track can't be null.");
        }
        if (!p.getTracks().contains(t)) {
            throw new IllegalArgumentException("This track isn't in the playlist.");
        }
        AppCommand command = new RemoveTrackFromPlaylistCommand(p, t);
        commandManager.execute(command);
        playlistLibrary.updatePlaylist(p); 
    }

    /**
     * Delega l'operazione di undo al CommandManager.
     */
     public void undo(){
        commandManager.undo();
    }

    /**
     * @brief Modifica l'ordine di una traccia nella playlist.
     * @throws IllegalArgumentException Se la playlist è autogenerata.
     */
    public void reorderTrack(Track t, Playlist p, int newIndex) throws Exception {
        if (p.isAutoGenerated()) {
            throw new IllegalArgumentException("Impossibile riordinare manualmente una playlist autogenerata.");
        }
        AppCommand reorderCommand = new ReorderTrackCommand(p, t, newIndex);
        try {
            this.commandManager.execute(reorderCommand);
        } catch (Exception e) {
            this.commandManager.undo(); 
            throw new Exception("Errore durante il salvataggio del nuovo ordine. L'operazione è stata annullata.", e);
        }
    }

    /**
     * @brief Crea o aggiorna la playlist automatica associata al tag specificato.
     *
     * @details Verifica se nella PlaylistLibrary esiste già una playlist autogenerata
     *          il cui nome corrisponde al nome del tag (Tag#name(), case-insensitive).
     *          - Se non esiste: invoca TagPlaylistCreator per costruirla e la aggiunge
     *            direttamente alla PlaylistLibrary (operazione di sistema non reversibile
     *            dall'utente, quindi senza passare per CommandManager).
     *          - Se esiste già: aggiorna la lista delle tracce sostituendo il contenuto
     *            con quello prodotto dal creator aggiornato, poi notifica gli observer
     *            tramite PlaylistLibrary#updatePlaylist(Playlist).
     *          Se il creator non produce alcuna playlist (nessuna traccia con il tag)
     *          e non esiste già una playlist per quel tag, non viene creato nulla.
     *
     * @param tag Il tag per cui aggiornare o creare la playlist automatica.
     *            Viene ignorato se null.
     */
    public void createAutoPlaylist(Tag tag) {
        if (tag == null) {
            return;
        }

        Playlist existing = findAutoPlaylistByName(tag.name());

        TagPlaylistCreator creator = new TagPlaylistCreator(tag);
        Playlist updated = creator.createPlaylist(trackLibrary.getTracks());

        if (existing == null) {
            if (updated != null) {
                playlistLibrary.addPlaylist(updated);
            }
        } else {
            existing.getTracks().clear();
            if (updated != null) {
                for (Track t : updated.getTracks()) {
                    existing.getTracks().add(t);
                }
            }
            playlistLibrary.updatePlaylist(existing);
        }
    }

    /**
     * @brief Rimuove la playlist automatica del tag se nessuna traccia lo possiede più.
     *
     * @details Dopo la rimozione di un tag da una traccia (TrackController#removeTag),
     *          verifica se nella libreria rimane ancora almeno una traccia il cui
     *          TagSet contiene il tag specificato. Se non ne rimane nessuna, elimina
     *          la corrispondente playlist autogenerata dalla PlaylistLibrary,
     *          notificando automaticamente gli observer.
     *
     * @param tag Il tag appena rimosso dalla traccia. Viene ignorato se null.
     */
    public void removeTagPlaylistIfEmpty(Tag tag) {
        if (tag == null) {
            return;
        }

        boolean tagStillPresent = trackLibrary.getTracks().stream()
                .anyMatch(t -> t.getTagSet().hasTag(tag));

        if (!tagStillPresent) {
            Playlist toRemove = findAutoPlaylistByName(tag.name());
            if (toRemove != null) {
                playlistLibrary.removePlaylist(toRemove);
            }
        }
    }

    /**
     * @brief Crea o aggiorna la playlist automatica associata al genere specificato.
     *
     * @details Verifica se nella PlaylistLibrary esiste già una playlist autogenerata
     *          il cui nome corrisponde al genere (confronto case-insensitive).
     *          - Se non esiste: invoca GenrePlaylistCreator per costruirla
     *            e la aggiunge direttamente alla PlaylistLibrary (senza passare per
     *            CommandManager, perché è un'operazione di sistema non reversibile dall'utente).
     *          - Se esiste già: aggiorna la lista delle tracce sostituendo il contenuto
     *            con quello prodotto dal creator aggiornato, poi notifica gli observer
     *            tramite PlaylistLibrary#updatePlaylist(Playlist).
     *          In entrambi i casi la PlaylistLibrary notifica gli observer.
     *
     * @param genre Il genere musicale per cui aggiornare o creare la playlist automatica.
     *              Viene ignorato se null o blank.
     */
    
    public void createAutoPlaylist(String genre) {
        if (genre == null || genre.isBlank()) {
            return;
        }
        // Cerca se esiste già una playlist autogenerata per questo genere
        Playlist existing = findAutoPlaylistByName(genre);

        GenrePlaylistCreator creator = new GenrePlaylistCreator(genre);
        Playlist updated = creator.createPlaylist(trackLibrary.getTracks());

        if (existing == null) {
            if (updated != null) {
                playlistLibrary.addPlaylist(updated);
            }
        } else {
            existing.getTracks().clear();
            if (updated != null) {
                for (Track t : updated.getTracks()) {
                    existing.getTracks().add(t);
                }
            }
            playlistLibrary.updatePlaylist(existing);
        }
    }
    
    /**
     * @brief Rimuove la playlist automatica di genere se non esistono più tracce di quel genere.
     *
     * @details Dopo la rimozione di una traccia dalla TrackLibrary, verifica se nella
     *          libreria rimangono ancora tracce con il genere specificato.
     *          Se non ne rimane nessuna, elimina la corrispondente playlist autogenerata
     *          dalla PlaylistLibrary, notificando automaticamente gli observer.
     *
     * @param genre Il genere della traccia appena rimossa. Viene ignorato se null o blank.
     */
    public void removeGenrePlaylistIfEmpty(String genre) {
        if (genre == null || genre.isBlank()) {
            return;
        }
        boolean genreStillPresent = trackLibrary.getTracks().stream()
                .anyMatch(t -> genre.equalsIgnoreCase(t.getGenre()));

        if (!genreStillPresent) {
            Playlist toRemove = findAutoPlaylistByName(genre);
            if (toRemove != null) {
                playlistLibrary.removePlaylist(toRemove);
            }
        }
    }

    
    /**
     * @brief Crea o aggiorna la playlist automatica associata all'anno specificato.
     *
     * @details Verifica se esiste già una playlist autogenerata il cui nome corrisponde all'anno (come stringa).
     *          - Se non esiste: invoca YearPlaylistCreator per costruirla e la aggiunge
     *            direttamente alla PlaylistLibrary.
     *          - Se esiste già: aggiorna il contenuto con le tracce aggiornate.
     *          Viene ignorato se year <= 0.
     *
     * @param year L'anno di pubblicazione per cui aggiornare o creare la playlist automatica. 
     */
    
    public void createAutoPlaylist(int year) {
        if (year <= 0) {
                    return;
                }
        YearPlaylistCreator creator = new YearPlaylistCreator(year);
        String decadeName = creator.getDecadeName();
        Playlist existing = findAutoPlaylistByName(decadeName);
        Playlist updated = creator.createPlaylist(trackLibrary.getTracks());

        if (existing == null) {
            if (updated != null) {
                playlistLibrary.addPlaylist(updated);
            }
        } else {
            existing.getTracks().clear();
            if (updated != null) {
                for (Track t : updated.getTracks()) {
                    existing.getTracks().add(t);
                }
            }
            playlistLibrary.updatePlaylist(existing);
        }
    }

    /**
     * @brief Rimuove la playlist automatica di anno se non esistono più tracce di quell'anno.
     *
     * @details Dopo la rimozione di una traccia dalla TrackLibrary, verifica se rimangono ancora tracce con quell'anno.
     *          Se non ne rimane nessuna, elimina la corrispondente playlist autogenerata.
     *
     * @param year L'anno della traccia appena rimossa. Viene ignorato se <= 0.
     */
    public void removeYearPlaylistIfEmpty(int year) {
        if (year <= 0) {
            return;
        }
        YearPlaylistCreator creator = new YearPlaylistCreator(year);
        int decadeStart = creator.getDecadeStart();
        String decadeName = creator.getDecadeName();

        boolean decadeStillPresent = trackLibrary.getTracks().stream()
                .anyMatch(t -> t.getYear() >= decadeStart && t.getYear() <= decadeStart + 9);

        if (!decadeStillPresent) {
            Playlist toRemove = findAutoPlaylistByName(decadeName);
            if (toRemove != null) {
                playlistLibrary.removePlaylist(toRemove);
            }
        }
    }
    


    /**
     * @brief Crea o aggiorna la playlist automatica "Most_played" con le tracce più riprodotte.
     *
     * @details Invoca MostPlayedPlaylistCreator per produrre una playlist ordinata per
     *          playCount decrescente (solo tracce con almeno una riproduzione).
     *          - Se non esiste: la aggiunge alla PlaylistLibrary.
     *          - Se esiste già: ne sostituisce il contenuto e notifica gli observer.
     *          Se il creator restituisce null (nessuna traccia riprodotta) e la playlist
     *          non esiste, non viene creato nulla. Se esiste e il creator restituisce null,
     *          la playlist viene svuotata ma mantenuta (sarà rimossa da removeTopPlayedIfEmpty).
     */
    public void createAutoMostPlayedPlaylist() {
        Playlist existing = findAutoPlaylistByName(MostPlayedPlaylistCreator.PLAYLIST_NAME);

        MostPlayedPlaylistCreator creator = new MostPlayedPlaylistCreator();
        Playlist updated = creator.createPlaylist(trackLibrary.getTracks());

        if (existing == null) {
            if (updated != null) {
                playlistLibrary.addPlaylist(updated);
            }
        } else {
            existing.getTracks().clear();
            if (updated != null) {
                for (Track t : updated.getTracks()) {
                    existing.getTracks().add(t);
                }
            }
            playlistLibrary.updatePlaylist(existing);
        }
    }

    /**
     * @brief Rimuove la playlist "Most_played" se nessuna traccia ha ancora riproduzioni.
     *
     * @details Chiamato dopo la cancellazione di una traccia dalla libreria, per verificare
     *          se rimangono ancora tracce con playCount > 0. Se non ne rimane nessuna,
     *          elimina la playlist autogenerata.
     */
    public void removeTopPlayedPlaylistIfEmpty() {
        boolean anyPlayed = trackLibrary.getTracks().stream()
                .anyMatch(t -> t.getPlayCount() > 0);

        if (!anyPlayed) {
            Playlist toRemove = findAutoPlaylistByName(MostPlayedPlaylistCreator.PLAYLIST_NAME);
            if (toRemove != null) {
                playlistLibrary.removePlaylist(toRemove);
            }
        }
    }

    /**
     * @brief Cerca nella PlaylistLibrary una playlist autogenerata con il nome specificato.
     *
     * @details Usato internamente da createAutoPlay(String) e
     *         removeGenrePlaylistIfEmpty(String) per evitare duplicazioni di ricerca.
     *          Il confronto sul nome è case-insensitive e considera solo le playlist
     *          con isAutoGenerated() == true.
     *
     * @param name Il nome da cercare (corrisponde al genere per le playlist di genere).
     * @return La playlist trovata, oppure null se non esiste.
     */
    private Playlist findAutoPlaylistByName(String name) {
        for (Playlist p : playlistLibrary.getPlaylists()) {
            if (p.isAutoGenerated() && p.getName().equalsIgnoreCase(name)) {
                return p;
            }
        }
        return null;
    }
}
